// EduSchedule-test/frontend/components/app-layout.tsx
"use client"

import type React from "react"
import { Sidebar } from "./sidebar"
import { Header } from "./header"

interface AppLayoutProps {
  children: React.ReactNode
  activePage: string
  title: string
  subtitle?: string
  action?: React.ReactNode
}

export function AppLayout({ children, activePage, title, subtitle, action }: AppLayoutProps) {
  return (
    <div className="flex h-screen bg-gray-50">
      <Sidebar activePage={activePage} />
      <div className="flex-1 flex flex-col overflow-hidden">
        <Header title={title} subtitle={subtitle} action={action} />
        <main className="flex-1 overflow-y-auto p-6">
          {children}
        </main>
      </div>
    </div>
  )
}

// frontend-angular/src/app/shared/components/app-layout/app-layout.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SidebarComponent } from '../sidebar/sidebar.component';
import { HeaderComponent } from '../header/header.component';

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [CommonModule, SidebarComponent, HeaderComponent],
  template: `
    <div class="flex h-screen bg-gray-50">
      <app-sidebar [activePage]="activePage"></app-sidebar>
      <div class="flex-1 flex flex-col overflow-hidden">
        <app-header [title]="title" [subtitle]="subtitle">
          <ng-content select="[header-actions]"></ng-content>
        </app-header>
        <main class="flex-1 overflow-y-auto p-6">
          <ng-content></ng-content>
        </main>
      </div>
    </div>
  `
})
export class AppLayoutComponent {
  @Input() activePage: string = '';
  @Input() title: string = '';
  @Input() subtitle?: string;
}
