// EduSchedule-test/frontend/components/sidebar.tsx
"use client"

import {
  Calendar,
  LayoutDashboard,
  Users,
  Clock,
  BookOpen,
  Package,
  AlertTriangle,
  BarChart3,
  Bell,
  LogOut,
  User,
  UserCheck,
  Settings,
  School,
  Brain,
  TrendingUp,
} from "lucide-react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { useAuth } from "@/contexts/auth-context"
import { useToast } from "@/contexts/toast-context"
import { PermissionGate } from "@/components/permission-gate"

const menuItems = [
  {
    icon: LayoutDashboard,
    label: "Tableau de bord",
    href: "/dashboard",
    key: "dashboard",
    roles: ["admin", "teacher", "student"],
  },
  { 
    icon: User, 
    label: "Mon Profil", 
    href: "/profile", 
    key: "profile", 
    roles: ["admin", "teacher", "student"] 
  },
  
  // Section Gestion des utilisateurs
  { 
    icon: Users, 
    label: "Utilisateurs", 
    href: "/users", 
    key: "users", 
    roles: ["admin"] 
  },
  { 
    icon: School, 
    label: "Écoles", 
    href: "/schools", 
    key: "schools", 
    roles: ["admin"] 
  },
  
  // Section Planning et Emplois du temps
  {
    icon: Clock,
    label: "Emplois du temps",
    href: "/schedule",
    key: "schedule",
    roles: ["admin", "teacher", "student"],
  },
  {
    icon: Calendar,
    label: "Calendrier",
    href: "/calendar",
    key: "calendar",
    roles: ["admin", "teacher", "student"],
  },
  { 
    icon: UserCheck, 
    label: "Disponibilités", 
    href: "/teacher-availability", 
    key: "teacher-availability", 
    roles: ["admin", "teacher"] 
  },
  
  // Section Réservations et Ressources
  {
    icon: Calendar,
    label: "Réservation salles",
    href: "/reservations",
    key: "reservations",
    roles: ["admin", "teacher"],
  },
  { 
    icon: Package, 
    label: "Ressources", 
    href: "/resources", 
    key: "resources", 
    roles: ["admin", "teacher"] 
  },
  
  // Section Cours et Formation
  { 
    icon: BookOpen, 
    label: "Cours & Groupes", 
    href: "/courses", 
    key: "courses", 
    roles: ["admin", "teacher"] 
  },
  
  // Section Gestion et Monitoring
  { 
    icon: AlertTriangle, 
    label: "Conflits", 
    href: "/conflicts", 
    key: "conflicts", 
    roles: ["admin"], 
    badge: 3 
  },
  {
    icon: Bell,
    label: "Notifications",
    href: "/notifications",
    key: "notifications",
    roles: ["admin", "teacher", "student"],
    badge: 2,
  },
  
  // Section Analytics et Rapports
  { 
    icon: BarChart3, 
    label: "Rapports", 
    href: "/reports", 
    key: "reports", 
    roles: ["admin"] 
  },
  { 
    icon: TrendingUp, 
    label: "Analytics", 
    href: "/analytics", 
    key: "analytics", 
    roles: ["admin"] 
  },
  { 
    icon: Brain, 
    label: "IA Prédictive", 
    href: "/ai-insights", 
    key: "ai-insights", 
    roles: ["admin"] 
  },
]

interface SidebarProps {
  activePage?: string
}

export function Sidebar({ activePage = "dashboard" }: SidebarProps) {
  const router = useRouter()
  const { user, logout } = useAuth()
  const { addToast } = useToast()

  const handleLogout = async () => {
    try {
      await logout()
      addToast("Déconnecté avec succès", "success")
      router.push("/login")
    } catch (error) {
      addToast("Erreur lors de la déconnexion", "error")
    }
  }

  if (!user) return null

  return (
    <aside className="w-64 bg-[#1F2937] text-white flex flex-col">
      <div className="p-6 flex items-center gap-3">
        <div className="w-12 h-12 bg-[#FBBF24] rounded-xl flex items-center justify-center">
          <Calendar className="w-6 h-6 text-[#1F2937]" />
        </div>
        <div>
          <h1 className="font-bold text-lg">EduSchedule</h1>
          <p className="text-sm text-gray-400">Gestion intelligente</p>
        </div>
      </div>

      <div className="px-4 py-3 bg-[#374151] mx-4 rounded-lg flex items-center gap-3">
        <img src={user.avatar || "/placeholder.svg"} alt={user.name} className="w-10 h-10 rounded-full" />
        <div className="flex-1">
          <p className="font-semibold text-sm">{user.name}</p>
          <p className="text-xs text-gray-400 capitalize">{user.role}</p>
        </div>
      </div>

      <nav className="flex-1 px-3 py-6 space-y-1 overflow-y-auto">
        {menuItems.map((item) => (
          <PermissionGate key={item.key} requiredRoles={item.roles as any}>
            <Link
              href={item.href}
              className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg transition-colors relative ${
                activePage === item.key ? "bg-[#15803D] text-white" : "text-gray-300 hover:bg-[#374151]"
              }`}
            >
              <item.icon className="w-5 h-5" />
              <span className="text-sm font-medium">{item.label}</span>
              {item.badge && (
                <span className="ml-auto bg-red-500 text-white text-xs font-bold rounded-full w-5 h-5 flex items-center justify-center">
                  {item.badge}
                </span>
              )}
            </Link>
          </PermissionGate>
        ))}
      </nav>

      <button
        onClick={handleLogout}
        className="mx-3 mb-6 flex items-center gap-3 px-3 py-2.5 rounded-lg text-gray-300 hover:bg-[#374151] transition-colors w-full"
      >
        <LogOut className="w-5 h-5" />
        <span className="text-sm font-medium">Déconnexion</span>
      </button>
    </aside>
  )
}

// frontend-angular/src/app/shared/components/sidebar/sidebar.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { 
  Calendar, LayoutDashboard, Users, Clock, BookOpen, 
  Package, AlertTriangle, BarChart3, Bell, LogOut, 
  User, UserCheck, Settings, School, Brain, TrendingUp 
} from 'lucide-angular';

interface MenuItem {
  icon: any;
  label: string;
  href: string;
  key: string;
  roles: string[];
  badge?: string | number;
}

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent {
  @Input() activePage: string = 'dashboard';
  
  menuItems: MenuItem[] = [
    {
      icon: LayoutDashboard,
      label: 'Tableau de bord',
      href: '/dashboard',
      key: 'dashboard',
      roles: ['admin', 'teacher', 'student']
    },
    {
      icon: User,
      label: 'Mon Profil',
      href: '/profile',
      key: 'profile',
      roles: ['admin', 'teacher', 'student']
    },
    {
      icon: Users,
      label: 'Utilisateurs',
      href: '/users',
      key: 'users',
      roles: ['admin']
    },
    {
      icon: School,
      label: 'Écoles',
      href: '/schools',
      key: 'schools',
      roles: ['admin']
    },
    {
      icon: Clock,
      label: 'Emplois du temps',
      href: '/schedule',
      key: 'schedule',
      roles: ['admin', 'teacher', 'student']
    },
    {
      icon: Calendar,
      label: 'Calendrier',
      href: '/calendar',
      key: 'calendar',
      roles: ['admin', 'teacher', 'student']
    },
    {
      icon: UserCheck,
      label: 'Disponibilités',
      href: '/teacher-availability',
      key: 'teacher-availability',
      roles: ['admin', 'teacher']
    },
    {
      icon: Calendar,
      label: 'Réservation salles',
      href: '/reservations',
      key: 'reservations',
      roles: ['admin', 'teacher']
    },
    {
      icon: Package,
      label: 'Ressources',
      href: '/resources',
      key: 'resources',
      roles: ['admin', 'teacher']
    },
    {
      icon: BookOpen,
      label: 'Cours & Groupes',
      href: '/courses',
      key: 'courses',
      roles: ['admin', 'teacher']
    },
    {
      icon: AlertTriangle,
      label: 'Conflits',
      href: '/conflicts',
      key: 'conflicts',
      roles: ['admin'],
      badge: 3
    },
    {
      icon: Bell,
      label: 'Notifications',
      href: '/notifications',
      key: 'notifications',
      roles: ['admin', 'teacher', 'student'],
      badge: 2
    },
    {
      icon: BarChart3,
      label: 'Rapports',
      href: '/reports',
      key: 'reports',
      roles: ['admin']
    },
    {
      icon: TrendingUp,
      label: 'Analytics',
      href: '/analytics',
      key: 'analytics',
      roles: ['admin']
    },
    {
      icon: Brain,
      label: 'IA Prédictive',
      href: '/ai-insights',
      key: 'ai-insights',
      roles: ['admin']
    },
    {
      icon: Settings,
      label: 'Paramètres',
      href: '/settings',
      key: 'settings',
      roles: ['admin']
    }
  ];

  currentUser = {
    name: 'Admin User',
    role: 'admin',
    avatar: '/assets/avatar.png'
  };

  onLogout() {
    // TODO: Implement logout logic
    console.log('Logout clicked');
  }
}

<aside class="w-64 bg-[#1F2937] text-white flex flex-col h-screen">
  <!-- Logo -->
  <div class="p-6 flex items-center gap-3">
    <div class="w-12 h-12 bg-[#FBBF24] rounded-xl flex items-center justify-center">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-[#1F2937]">
        <rect width="18" height="18" x="3" y="4" rx="2" ry="2"/>
        <line x1="16" x2="16" y1="2" y2="6"/>
        <line x1="8" x2="8" y1="2" y2="6"/>
        <line x1="3" x2="21" y1="10" y2="10"/>
      </svg>
    </div>
    <div>
      <h1 class="font-bold text-lg">EduSchedule</h1>
      <p class="text-sm text-gray-400">Gestion intelligente</p>
    </div>
  </div>

  <!-- User Info -->
  <div class="px-4 py-3 bg-[#374151] mx-4 rounded-lg flex items-center gap-3">
    <img [src]="currentUser.avatar" [alt]="currentUser.name" class="w-10 h-10 rounded-full bg-gray-500" />
    <div class="flex-1">
      <p class="font-semibold text-sm">{{ currentUser.name }}</p>
      <p class="text-xs text-gray-400 capitalize">{{ currentUser.role }}</p>
    </div>
  </div>

  <!-- Navigation -->
  <nav class="flex-1 px-3 py-6 space-y-1 overflow-y-auto">
    <a *ngFor="let item of menuItems"
       [routerLink]="item.href"
       routerLinkActive="bg-[#15803D] text-white"
       [routerLinkActiveOptions]="{exact: false}"
       class="w-full flex items-center gap-3 px-3 py-2.5 rounded-lg transition-colors relative text-gray-300 hover:bg-[#374151]">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="w-5 h-5">
        <!-- Icons will be rendered here -->
      </svg>
      <span class="text-sm font-medium">{{ item.label }}</span>
      <span *ngIf="item.badge" class="ml-auto bg-red-500 text-white text-xs font-bold rounded-full w-5 h-5 flex items-center justify-center">
        {{ item.badge }}
      </span>
    </a>
  </nav>

  <!-- Logout Button -->
  <button (click)="onLogout()" class="mx-3 mb-6 flex items-center gap-3 px-3 py-2.5 rounded-lg text-gray-300 hover:bg-[#374151] transition-colors w-full">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="w-5 h-5">
      <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/>
      <polyline points="16 17 21 12 16 7"/>
      <line x1="21" x2="9" y1="12" y2="12"/>
    </svg>
    <span class="text-sm font-medium">Déconnexion</span>
  </button>
</aside>
